version: "3.8"

services:
  nodejs-server:
    build: .
    container_name: nodejs-server
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      - ./src/WebServer/config/.env.main
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    command: ["mongod", "--quiet", "--bind_ip_all", "--logpath", "/dev/null"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  recommend-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: recommend-server
    ports:
      - "${CPP_PORT}:${CPP_PORT}"
    command: ["${CPP_PORT}"]

  react-client:
    build:
      context: ./src/web_app
      dockerfile: Dockerfile
    container_name: react-client
    ports:
      - "${REACT_PORT}:${REACT_PORT}"
    environment:
      - PORT=${REACT_PORT}

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local